<?php
/**
 * Implements hook_block_info().
 */
function services_carousel_blocks_block_info() {
  $blocks['our_services_carousel'] = array(
    'info' => t('Our services carousel'),
    'title' => NULL,
	'cache' => DRUPAL_NO_CACHE
  );
  $blocks['gallery_carousel'] = array(
    'info' => t('Gallery Carousel'),
    'title' => NULL,
	'cache' => DRUPAL_NO_CACHE
  );
  $blocks['other_services'] = array(
    'info' => t('Other Services'),
    'title' => NULL,
	'cache' => DRUPAL_NO_CACHE
	
  );
  $blocks['popular_conatainer_carousel'] = array(
    'info' => t('Popular Containers'),
    'title' => NULL,
	'cache' => DRUPAL_NO_CACHE
	
  );
  $blocks['service_page_gallley_carousel'] = array(
    'info' => t('Service page Gallery'),
    'title' => NULL,
	'cache' => DRUPAL_NO_CACHE
	
  );
  $blocks['about_section_services'] = array(
    'info' => t('About Section Services'),
    'title' => NULL,
	'cache' => DRUPAL_NO_CACHE
	
  );
  $blocks['pest_control_carousel'] = array(
    'info' => t('Pest Control Gallery'),
    'title' => NULL,
	'cache' => DRUPAL_NO_CACHE
	
  );
  $blocks['waste_enquiry_form'] = array(
    'info' => t('Commercial recycling waste enquiry form'),
    'title' => NULL,	
  );
  /*$blocks['other_services1'] = array(
    'info' => t('Other Services1'),
    'title' => NULL,
	
  );*/
  
  return $blocks;
}
/**
 * Implements hook_block_view().
*/
function services_carousel_blocks_block_view($delta = '') {
  if ($delta == 'our_services_carousel') {
    $block['subject'] = t('Our Services');
    $block['content'] = services_carousel_blocks_our_services_carousel();
  }
  if ($delta == 'gallery_carousel') {
    $block['subject'] = t('Gallery');
    $block['content'] = services_carousel_blocks_gallery_carousel();
  }
  if ($delta == 'other_services') {
    $block['subject'] = t('Other Services');
    $block['content'] = services_carousel_blocks_other_services();
  }
  /*if ($delta == 'other_services1') {
    $block['subject'] = t('<h3 class="block-title">Other Services</h3>');
    $block['content'] = services_carousel_blocks_other_services();
  }*/
  if ($delta == 'popular_conatainer_carousel') {
    $block['subject'] = t('Popular Containers');
    $block['content'] = services_carousel_blocks_popular_conatainer();
  }
  if ($delta == 'service_page_gallley_carousel') {
    
    $nid = arg(1);
	$node = node_load($nid);
	
	$gallery_title = field_get_items('node', $node, 'field_gallery_title', $node->language);
	
	$gallery_image = field_get_items('node', $node, 'field_gallery_image', $node->language);
	if($node->type == 'services' && !empty($gallery_image) && !empty($gallery_title))
	{
		$block['subject'] = t($gallery_title[0]['value']);
    	$block['content'] = services_carousel_blocks_service_page_gallery();
	} else {
	
		$block['subject'] = '';
    	$block['content'] = '';
	}
  }
  
  if ($delta == 'about_section_services') {
    $block['subject'] = t('');
    $block['content'] = services_carousel_blocks_about_services();
  }
  if ($delta == 'pest_control_carousel') {
    $block['subject'] = t('Gallery');
    $block['content'] = services_carousel_blocks_pest_carousel();
  }
   if($delta == 'waste_enquiry_form') {
	$block['subject'] = t('');
    $block['content'] = commercial_waste_enquiry_form_content();
  }
  return $block;
}
function commercial_waste_enquiry_form_content() {
	return drupal_get_form('commercial_waste_enquiry_form');
}
function commercial_waste_enquiry_form(){
	$markup_text1 = "If you are unsure of what size bin or waste type you may require, please just fill in your contact details and one of our customer service officers will give you a call back to arrange site visit.";
	
	$markup_text2 = "If you have no space or are restricted for containers, please select sacks as below.";
	
	$frequency_option = array(
			'' => 'None',
			'Daily' => 'Daily',
			'Weekly' => 'Weekly',
			'Fortnightly' => 'Fortnightly',  	  	
			'Monthly ' => 'Monthly ',  	  	  
	);
	
	$form['name'] = array(
		'#type' => 'textfield',
		'#title' => t('Customer Name:'),		
		'#default_value' => '',	
		'#required' => TRUE, 
		'#prefix'=>'<div id="form-message"></div><div class="customer-detail">',				
	);
	$form['telephone'] = array(
	   '#type' => 'textfield',
       '#title' => t('Phone Number:'),		   
       '#default_value' => '', 
	   '#required' => TRUE,   
	);
	$form['email'] = array(
	   '#type' => 'textfield',
       '#title' => t('Email Address:'),		   
       '#default_value' => '',  
	   '#required' => TRUE,  
	);
	$form['business'] = array(
	   '#type' => 'textfield',
       '#title' => t('Business Name:'),	 	   
	   '#resizable' => FALSE,               
	   '#required' => TRUE,
	   //'#suffix'=>'</div>',  
	);
	
	$form['address'] = array(
	   '#type' => 'select',
       '#title' => t('Address:'),	   
	   '#options' => array('' => t('Select')),	
	   '#attributes' => array('class' => array('address-input')),  	   
	   '#validated' => TRUE, 
	   //'#suffix'=>'</div>',                
	   //'#required' => TRUE,    	   
	);
	
	$form['postcode'] = array(
	   '#type' => 'textfield',
       '#title' => t('Postcode:'),
	   '#prefix'=> "<div class='postcode-control'>",
	   '#suffix'=>'<button id="address_lookup" type="button" class="btn btn-default">Find Address</button></div></div>',	   		          
       '#default_value' => '', 
	   '#attributes' => array('class' => array('postcode-input')), 
	   '#required' => TRUE,  
	); 	
		
	$form['markup_text1'] = array(
	   '#type' => 'markup',
       '#markup' => $markup_text1, 
	   '#prefix'=>'<div class="markup-text1">',
	   '#suffix'=>'</div>',
	);
	$form['mixed_recycling'] = array(
	   '#type' => 'markup',
       '#markup' => 'Mixed Recycling:', 
	   '#prefix'=>'<div class="markup-text">',
	   '#suffix'=>'</div>',
	);
	$form['mixed_1100'] = array(
	   '#type' => 'checkbox',
       '#title' => t(''),
	   '#default_value' => array(),
	   '#theme_wrappers' => array(),
	   '#attributes'=> array('class'=>array('hidden')),
	   '#prefix'=>'<div class="row"><div class="col-md-3"><label class="checkbox-image"><img src="/sites/all/themes/oxford/images/bin-img/1100L General Waste Bin.jpg" alt="..." class="img-thumbnail img-check" /><span class="bin-title">1100 Litre</span>',  
	   '#suffix'=>'</label>',  
	);
	$form['mixed_1100_no'] = array(
	   '#type' => 'textfield',             
       '#default_value' => '', 
	   '#attributes'=> array('placeholder'=>array('No. of bins'), 'disabled' => 'disabled'),	   
	   '#suffix'=>'</div>',   
	);
	$form['mixed_820'] = array(
	   '#type' => 'checkbox',
       '#title' => t(''),
	   '#default_value' => array(),
	   '#theme_wrappers' => array(),
	   '#attributes'=> array('class'=>array('hidden')),
	   '#prefix'=>'<div class="col-md-3"><label class="checkbox-image"><img src="/sites/all/themes/oxford/images/bin-img/820L General Waste Green_1.jpg" alt="..." class="img-thumbnail img-check" /><span class="bin-title">820 Litre</span>',  
	   '#suffix'=>'</label>',  
	);
	$form['mixed_820_no'] = array(
	   '#type' => 'textfield',       
       '#default_value' => '', 
	   '#attributes'=> array('placeholder'=>array('No. of bins'), 'disabled' => 'disabled'),	   
	   '#suffix'=>'</div>',   
	);
	$form['mixed_360'] = array(
	   '#type' => 'checkbox',
       '#title' => t(''),
	   '#default_value' => array(),
	   '#theme_wrappers' => array(),
	   '#attributes'=> array('class'=>array('hidden')),
	   '#prefix'=>'<div class="col-md-3"><label class="checkbox-image"><img src="/sites/all/themes/oxford/images/bin-img/360L Grey and Black Lid Recycling.jpg" alt="..." class="img-thumbnail img-check" /><span class="bin-title">360 Litre</span>',  
	   '#suffix'=>'</label>',  
	);
	$form['mixed_360_no'] = array(
	   '#type' => 'textfield',       
       '#default_value' => '', 
	   '#attributes'=> array('placeholder'=>array('No. of bins'), 'disabled' => 'disabled'),	   
	   '#suffix'=>'</div>',   
	);
	$form['mixed_240'] = array(
	   '#type' => 'checkbox',
       '#title' => t(''),
	   '#default_value' => array(),
	   '#theme_wrappers' => array(),
	   '#attributes'=> array('class'=>array('hidden')),
	   '#prefix'=>'<div class="col-md-3"><label class="checkbox-image"><img src="/sites/all/themes/oxford/images/bin-img/240L Black Recycling.jpg" alt="..." class="img-thumbnail img-check" /><span class="bin-title">240 Litre</span>',  
	   '#suffix'=>'</label>',  
	);
	$form['mixed_240_no'] = array(
	   '#type' => 'textfield',       
       '#default_value' => '', 
	   '#attributes'=> array('placeholder'=>array('No. of bins'), 'disabled' => 'disabled'),	   
	   '#suffix'=>'</div></div>',   
	);
	$form['general_recycling'] = array(
	   '#type' => 'markup',
       '#markup' => 'General Waste:', 
	   '#prefix'=>'<div class="markup-text">',
	   '#suffix'=>'</div>',
	);
	$form['general_1100'] = array(
	   '#type' => 'checkbox',
       '#title' => t(''),
	   '#default_value' => array(),
	   '#theme_wrappers' => array(),
	   '#attributes'=> array('class'=>array('hidden')),
	   '#prefix'=>'<div class="row"><div class="col-md-3"><label class="checkbox-image"><img src="/sites/all/themes/oxford/images/bin-img/green/1100L-General-Waste-Bin-1.jpg" alt="..." class="img-thumbnail img-check" /><span class="bin-title">1100 Litre</span>',  
	   '#suffix'=>'</label>',  
	);
	$form['general_1100_no'] = array(
	   '#type' => 'textfield',             
       '#default_value' => '', 
	   '#attributes'=> array('placeholder'=>array('No. of bins'), 'disabled' => 'disabled'),	   
	   '#suffix'=>'</div>',   
	);
	$form['general_820'] = array(
	   '#type' => 'checkbox',
       '#title' => t(''),
	   '#default_value' => array(),
	   '#theme_wrappers' => array(),
	   '#attributes'=> array('class'=>array('hidden')),
	   '#prefix'=>'<div class="col-md-3"><label class="checkbox-image"><img src="/sites/all/themes/oxford/images/bin-img/green/820L-General-Waste-Green-1.jpg" alt="..." class="img-thumbnail img-check" /><span class="bin-title">820 Litre</span>',  
	   '#suffix'=>'</label>',  
	);
	$form['general_820_no'] = array(
	   '#type' => 'textfield',       
       '#default_value' => '', 
	   '#attributes'=> array('placeholder'=>array('No. of bins'), 'disabled' => 'disabled'),	   
	   '#suffix'=>'</div>',   
	);
	$form['general_360'] = array(
	   '#type' => 'checkbox',
       '#title' => t(''),
	   '#default_value' => array(),
	   '#theme_wrappers' => array(),
	   '#attributes'=> array('class'=>array('hidden')),
	   '#prefix'=>'<div class="col-md-3"><label class="checkbox-image"><img src="/sites/all/themes/oxford/images/bin-img/green/360L Green General Waste Bin.jpg" alt="..." class="img-thumbnail img-check" /><span class="bin-title">360 Litre</span>',  
	   '#suffix'=>'</label>',  
	);
	$form['general_360_no'] = array(
	   '#type' => 'textfield',       
       '#default_value' => '', 
	   '#attributes'=> array('placeholder'=>array('No. of bins'), 'disabled' => 'disabled'),	   
	   '#suffix'=>'</div>',   
	);
	$form['general_240'] = array(
	   '#type' => 'checkbox',
       '#title' => t(''),
	   '#default_value' => array(),
	   '#theme_wrappers' => array(),
	   '#attributes'=> array('class'=>array('hidden')),
	   '#prefix'=>'<div class="col-md-3"><label class="checkbox-image"><img src="/sites/all/themes/oxford/images/bin-img/green/240L Green General Waste.jpg" alt="..." class="img-thumbnail img-check" /><span class="bin-title">240 Litre</span>',  
	   '#suffix'=>'</label>',  
	);
	$form['general_240_no'] = array(
	   '#type' => 'textfield',       
       '#default_value' => '', 
	   '#attributes'=> array('placeholder'=>array('No. of bins'), 'disabled' => 'disabled'),	   
	   '#suffix'=>'</div></div>',   
	);
	$form['food_recycling'] = array(
	   '#type' => 'markup',
       '#markup' => 'Food Waste Recycling:', 
	   '#prefix'=>'<div class="markup-text">',
	   '#suffix'=>'</div>',
	);
	$form['food_120'] = array(
	   '#type' => 'checkbox',
       '#title' => t(''),
	   '#default_value' => array(),
	   '#theme_wrappers' => array(),
	   '#attributes'=> array('class'=>array('hidden')),
	   '#prefix'=>'<div class="row"><div class="col-md-3"><label class="checkbox-image"><img src="/sites/all/themes/oxford/images/bin-img/240-Red-Food-Bin-small.jpg" alt="..." class="img-thumbnail img-check" /><span class="bin-title">120 Litre</span>',  
	   '#suffix'=>'</label>',  
	);
	$form['food_120_no'] = array(
	   '#type' => 'textfield',             
       '#default_value' => '', 
	   '#attributes'=> array('placeholder'=>array('No. of bins'), 'disabled' => 'disabled'),	   
	   '#suffix'=>'</div></div>',   
	);
	$form['glass_recycling'] = array(
	   '#type' => 'markup',
       '#markup' => 'Glass Recycling:', 
	   '#prefix'=>'<div class="markup-text">',
	   '#suffix'=>'</div>',
	);
	$form['glass_240'] = array(
	   '#type' => 'checkbox',
       '#title' => t(''),
	   '#default_value' => array(),
	   '#theme_wrappers' => array(),
	   '#attributes'=> array('class'=>array('hidden')),
	   '#prefix'=>'<div class="row"><div class="col-md-3"><label class="checkbox-image"><img src="/sites/all/themes/oxford/images/bin-img/240L Black Recycling.jpg" alt="..." class="img-thumbnail img-check" /><span class="bin-title">240 Litre</span>',  
	   '#suffix'=>'</label>',  
	);
	$form['glass_240_no'] = array(
	   '#type' => 'textfield',       
       '#default_value' => '', 
	   '#attributes'=> array('placeholder'=>array('No. of bins'), 'disabled' => 'disabled'),	   
	   '#suffix'=>'</div></div>',   
	);
	$form['markup_text2'] = array(
	   '#type' => 'markup',
       '#markup' => $markup_text2, 
	   '#prefix'=>'<div class="markup-text1">',
	   '#suffix'=>'</div>',
	);
	$form['markup_text3'] = array(
	   '#type' => 'markup',
       '#markup' => 'Sacks/Cardboard Labels:', 
	   '#prefix'=>'<div class="markup-text">',
	   '#suffix'=>'</div>',
	);	
	$form['mixed_sacks'] = array(
		'#type' => 'hidden',				
		'#default_value' => array(),
		'#theme_wrappers' => array(),
		'#attributes' => array ('id' => array('mixed_sacks')),		 
		'#prefix'=>'<div class="row"><div class="form-group"><label class="col-sm-8 col-md-8 control-label ">Mixed Recycling Sacks</label><div class="col-sm-4 col-md-4 text-right"><div class="radioBtn btn-group"><a class="sacks-btn active" data-toggle="mixed_sacks" data-title="Y">YES</a><a class="sacks-btn notActive" data-toggle="mixed_sacks" data-title="N">NO</a></div></div></div>',				
	);
	$form['cardbord_sacks'] = array(
		'#type' => 'hidden',				
		'#default_value' => array(),
		'#theme_wrappers' => array(),
		'#attributes' => array ('id' => array('cardbord_sacks')),		 
		'#prefix'=>'<div class="form-group"><label class="col-sm-8 col-md-8 control-label ">Cardboard Labels</label><div class="col-sm-4 col-md-4 text-right"><div class="radioBtn btn-group"><a class="sacks-btn active" data-toggle="cardbord_sacks" data-title="Y">YES</a><a class="sacks-btn notActive" data-toggle="cardbord_sacks" data-title="N">NO</a></div></div></div>',				
	);
	$form['general_sacks'] = array(
		'#type' => 'hidden',				
		'#default_value' => array(),
		'#theme_wrappers' => array(),
		'#attributes' => array ('id' => array('general_sacks')),		 
		'#prefix'=>'<div class="form-group"><label class="col-sm-8 col-md-8 control-label ">General Waste Sacks</label><div class="col-sm-4 col-md-4 text-right"><div class="radioBtn btn-group"><a class="sacks-btn active" data-toggle="general_sacks" data-title="Y">YES</a><a class="sacks-btn notActive" data-toggle="general_sacks" data-title="N">NO</a></div></div></div>',				
	);
	$form['food_sacks'] = array(
		'#type' => 'hidden',				
		'#default_value' => array(),
		'#theme_wrappers' => array(),
		'#attributes' => array ('id' => array('food_sacks')),		 
		'#prefix'=>'<div class="form-group"><label class="col-sm-8 col-md-8 control-label ">Food Waste Recycling Sacks</label><div class="col-sm-4 col-md-4 text-right"><div class="radioBtn btn-group"><a class="sacks-btn active" data-toggle="food_sacks" data-title="Y">YES</a><a class="sacks-btn notActive" data-toggle="food_sacks" data-title="N">NO</a></div></div></div>',		
		'#suffix'=>'</div>',				
	);
	$form['markup_text4'] = array(
	   '#type' => 'markup',
       '#markup' => 'Frequency of Collections:', 
	   '#prefix'=>'<div class="markup-text">',
	   '#suffix'=>'</div>',
	);
	$form['mixed_frequency'] = array(
		'#type' => 'select',
		'#title' => t('Mixed Recycling:'),			
		'#default_value' => '',	
		'#options' => $frequency_option,	
		'#attributes'=> array('data-id'=>array('mixed_frequency')),		
		'#prefix'=>'<div class="collection-detail">',				
	);
	$form['mixed_frequency_perweek'] = array(
	   '#type' => 'textfield',
       '#title' => '&nbsp;',
	   '#attributes'=> array('placeholder'=>array('Number of collection per week')),          
       '#default_value' => '', 	 
	   '#prefix'=>'<div id="mixed_frequency" class="frequency-number" style="display:none;">',
	   '#suffix'=>'</div>',	    
	);
	$form['general_frequency'] = array(
	   '#type' => 'select',
       '#title' => t('Genaral Waste:'),	          
       '#default_value' => '', 
	   '#attributes'=> array('data-id'=>array('general_frequency')), 
	   '#options' => $frequency_option,	   
	);
	$form['general_frequency_perweek'] = array(
	   '#type' => 'textfield',
       '#title' => '&nbsp;',
	   '#attributes'=> array('placeholder'=>array('Number of collection per week')),          
       '#default_value' => '', 	 
	   '#prefix'=>'<div id="general_frequency" class="frequency-number" style="display:none;">',
	   '#suffix'=>'</div>',	    
	);
	$form['food_frequency'] = array(
	   '#type' => 'select',
       '#title' => t('Food Waste Recycling:'),	          
       '#default_value' => '',
	   '#attributes'=> array('data-id'=>array('food_frequency')),   
	   '#options' => $frequency_option,	   
	);
	$form['food_frequency_perweek'] = array(
	   '#type' => 'textfield',
       '#title' => '&nbsp;',
	   '#attributes'=> array('placeholder'=>array('Number of collection per week')),          
       '#default_value' => '', 	 
	   '#prefix'=>'<div id="food_frequency" class="frequency-number" style="display:none;">',
	   '#suffix'=>'</div>',	    
	);
	$form['glass_frequency'] = array(
	   '#type' => 'select',
       '#title' => t('Glass Recycling:'),	          
       '#default_value' => '',
	   '#attributes'=> array('data-id'=>array('glass_frequency')),
	   '#options' => $frequency_option,  	   	   
	   //'#suffix'=>'</div>',  
	);
	$form['glass_frequency_perweek'] = array(
	   '#type' => 'textfield',
       '#title' => '&nbsp;',
	   '#attributes'=> array('placeholder'=>array('Number of collection per week')),          
       '#default_value' => '', 	 
	   '#prefix'=>'<div id="glass_frequency" class="frequency-number" style="display:none;">',
	   '#suffix'=>'</div></div>',	    
	);
	$form['other_comment'] = array(
	   '#type' => 'textarea',
       '#title' => t('Any Other Comments:'),
	   '#attributes'=> array('placeholder'=>array('Comment...')),          
       '#default_value' => '', 	 	   	    
	);	
	$form['submit'] = array(
		'#type' => 'submit',
		'#attributes' => array('class'=>array('green-btn')),
		'#prefix'=> '<div class="continue-btn">',
		'#suffix'=>'</div>',	
		'#value' => t('Submit'),		
	);
	
		
	return $form;
}
function commercial_waste_enquiry_form_submit($form, &$form_state){
	
	if(isset($form_state['values']) && !empty($form_state['values'])){
		$name = $form_state['values']['name'];
		$telephone = $form_state['values']['telephone'];
		$email = $form_state['values']['email'];
		$business = $form_state['values']['business'];
		$postcode = $form_state['values']['postcode'];
		$comment = $form_state['values']['other_comment'];
		$address = 'No Address Found.';
		
		if($form_state['values']['address']){
			$address = $form_state['values']['address'];
		}
		$m_1100 = '0';
		$m_820 = '0';
		$m_360 = '0';
		$m_240 = '0';
		
		if($form_state['values']['mixed_1100'] == 1){
			$m_1100 = $form_state['values']['mixed_1100_no'];
		}
		if($form_state['values']['mixed_820'] == 1){
			$m_820 = $form_state['values']['mixed_820_no'];
		}
		if($form_state['values']['mixed_360'] == 1){
			$m_360 = $form_state['values']['mixed_360_no'];
		}
		if($form_state['values']['mixed_240'] == 1){
			$m_240 = $form_state['values']['mixed_240_no'];
		}
		
		$g_1100 = '0';
		$g_820 = '0';
		$g_360 = '0';
		$g_240 = '0';
		
		if($form_state['values']['general_1100'] == 1){
			$g_1100 = $form_state['values']['general_1100_no'];
		}
		if($form_state['values']['general_820'] == 1){
			$g_820 = $form_state['values']['general_820_no'];
		}
		if($form_state['values']['general_360'] == 1){
			$g_360 = $form_state['values']['general_360_no'];
		}
		if($form_state['values']['general_240'] == 1){
			$g_240 = $form_state['values']['general_240_no'];
		}
		
		$f_120 = '0';
		
		if($form_state['values']['food_120'] == 1){
			$f_120 = $form_state['values']['food_120_no'];
		}
		
		$gl_240 = '0';
		
		if($form_state['values']['glass_240'] == 1){
			$gl_240 = $form_state['values']['glass_240_no'];
		}
		
		$m_sacks = 'Yes';
		
		if($form_state['values']['mixed_sacks'] == 'N'){
			$m_sacks = 'No';
		}
		
		$c_sacks = 'Yes';
		
		if($form_state['values']['cardbord_sacks'] == 'N'){
			$c_sacks = 'No';
		}
		
		$g_sacks = 'Yes';
		
		if($form_state['values']['general_sacks'] == 'N'){
			$g_sacks = 'No';
		}
		
		$f_sacks = 'Yes';
		
		if($form_state['values']['food_sacks'] == 'N'){
			$f_sacks = 'No';
		}
		
		$m_frequency = 'Not Available.';
		
		if($form_state['values']['mixed_frequency'] != ''){
			$m_frequency = $form_state['values']['mixed_frequency'];
		}
		
		$m_frequency_perweek = '';
		
		if($form_state['values']['mixed_frequency_perweek'] != ''){
			$m_frequency_perweek = "( ".$form_state['values']['mixed_frequency_perweek']." per week )";
		}
		
		$g_frequency = 'Not Available.';
		
		if($form_state['values']['general_frequency'] != ''){
			$g_frequency = $form_state['values']['general_frequency'];
		}
		
		$g_frequency_perweek = '';
		
		if($form_state['values']['general_frequency_perweek'] != ''){
			$g_frequency_perweek = "( ".$form_state['values']['general_frequency_perweek']." per week )";
		}
		
		$f_frequency = 'Not Available.';
		
		if($form_state['values']['food_frequency'] != ''){
			$f_frequency = $form_state['values']['food_frequency'];
		}
		
		$f_frequency_perweek = '';
		
		if($form_state['values']['food_frequency_perweek'] != ''){
			$f_frequency_perweek = "( ".$form_state['values']['food_frequency_perweek']." per week )";
		}
		
		$gl_frequency = 'Not Available.';
		
		if($form_state['values']['glass_frequency'] != ''){
			$gl_frequency = $form_state['values']['glass_frequency'];
		}
		
		$gl_frequency_perweek = '';
		
		if($form_state['values']['glass_frequency_perweek'] != ''){
			$gl_frequency_perweek = "( ".$form_state['values']['glass_frequency_perweek']." per week )";
		}
		
		$html1 = "<h1>Commercial recycling waste enquiry</h1>";
		$html1 .= "<h2>Personal Details</h2>	
				<p>Name   : ".$name."</p>
				<p>Telephone : ".$telephone."</p>
				<p>Email : ".$email."</p>
				<p>Business Name : ".$business."</p>
				<p>Address : ".$address."</p>
				<p>Postcode : ".$postcode."</p>
				<h2>Number & Type of Containers</h2>
				<table border='1' cellpadding='0' cellspacing='0'>
					<thead>
						<th colspan='2'><td>1100 Litres</td><td>820 Litres</td><td>360 Litres</td><td>240 Litres</td></th>
					</thead>
					<tbody>
						<tr><td colspan='2'><b>Mixed Recycling</b></td><td>".$m_1100."</td><td>".$m_820."</td><td>".$m_360."</td><td>".$m_240."</td></tr>
						<tr><td colspan='2'><b>General Waste</b></td><td>".$g_1100."</td><td>".$g_820."</td><td>".$g_360."</td><td>".$g_240."</td></tr>
					</tbody>
				</table>
				<br>
				<table border='1' cellpadding='0' cellspacing='0'>
					<thead>
						<th colspan='2'><td>120 Litres</td></th>
					</thead>
					<tbody>
						<tr><td colspan='2'><b>Food Waste Recycling</b></td><td>".$f_120."</td></tr>
					</tbody>
				</table>
				<br>
				<table border='1' cellpadding='0' cellspacing='0'>
					<thead>
						<th colspan='2'><td>240 Litres</td></th>
					</thead>
					<tbody>
						<tr><td colspan='2'><b>Glass Recycling</b></td><td>".$gl_240."</td></tr>
					</tbody>
				</table>
				<h2>Sacks/Cardboard Labels</h2>
				<p>Mixed Recycling Sacks : ".$m_sacks."</p>
				<p>Cardboard Labels : ".$c_sacks."</p>
				<p>General Waste Sacks : ".$g_sacks."</p>
				<p>Food Waste Recycling Sacks : ".$f_sacks."</p>
				<h2>Frequency of Collections</h2>
				<p>Mixed Recycling : ".$m_frequency." ".$m_frequency_perweek."</p>
				<p>General Waste : ".$g_frequency." ".$g_frequency_perweek."</p>
				<p>Food Waste Recycling : ".$f_frequency." ".$f_frequency_perweek."</p>
				<p>Glass Recycling  : ".$gl_frequency." ".$gl_frequency_perweek."</p>
				<p>Other Comment  : ".$comment."</p>
				";
				
		//echo $html;exit;
		//$mailto =  'dev.assertivemedia@gmail.com';		
		$mailto = 'tradewaste@oxford.gov.uk,businessdevelopment@oxford.gov.uk'; 
		$mailfrom ='no-reply@oxforddirectservices.co.uk';
		$params['subject'] = "Commercial recycling waste enquiry";
		$params['body'] = $html1;
		
		if (drupal_mail('oxford_mots', 'book_mots', $mailto, language_default(),$params,$mailfrom,TRUE)) 							 		{
			drupal_set_message(t('Your enquiry send successfully!!!'));

			$form_state['input'] = array();
  			$form_state['rebuild'] = TRUE;
		}
		else {
			drupal_set_message(t('<font color="red">Some Error in enquiry.</font>'));
		}
	}else{
		drupal_set_message(t('<font color="red">Some Error in enquiry.</font>'));
	}
}
/* Generate our services carousel */
function services_carousel_blocks_our_services_carousel(){
  		
		$query = new EntityFieldQuery();
		$query->entityCondition('entity_type', 'node')
		  ->entityCondition('bundle', 'services')
		  ->propertyCondition('status', NODE_PUBLISHED)		  
		  ->fieldCondition('field_service_category', 'tid', 'NULL', '!=')
		  ->addTag('filter_no_parent')
		  ->propertyOrderBy('created', 'DESC');
		  //->range(0,15);
		//print_r($query);
		$result = $query->execute();
		
		if (isset($result['node'])) {
	  		$nids = array_keys($result['node']);
	  		$nodes = entity_load('node', $nids);
		}else{
			$nodes = array();
		}
	
	  $services = $nodes;
	  //print_r($services); 	
	  
	 
	  //$array = array('Service1','Service2','Service3','Service4','Service5');
	  $output = '<div id="service-carousel" class="owl-carousel owl-theme">';
	  foreach ($services as $service) {
		  $alias = drupal_get_path_alias('node/'.$service->nid);
		  $banner = field_get_items('node', $service, 'field_service_image', $service->language);
		  $icon = field_get_items('node', $service, 'field_icon', $service->language);
		//$uri = $banner[0]['uri'];  // file path as uri: 'public://';
		$banner_img = file_create_url($banner[0]['uri']);
		$icon_img = file_create_url($icon[0]['uri']);
		$output .= '<div class="item">';
		$output .= '<div class="product-wrapper">';
		$output .= '<a href="/'.$alias.'"><div class="product" style="background-image:url('.$banner_img.');"></div>
		             <div class="product-content"> 					 
					 <div class="producut-icon" style="background-image: url('.$icon_img.');"></div>
					 <div class="product-title">'.truncate_utf8($service->title,40,TRUE,TRUE).'  <i class="fa fa-angle-right" aria-hidden="true"></i></div>
					 </div>
				   </a></div>';			
		$output .= '</div>';
	  }
	  $output .= '</div>';
	  /*$output .= '<div id="myCarousel2">
		<a class="left carousel-control" href="#" role="button" data-slide="prev">
<i class="fa fa-angle-left" aria-hidden="true"></i>
</a>
<a class="right carousel-control" href="#" role="button" data-slide="next">
<i class="fa fa-angle-right" aria-hidden="true"></i>
</a>		
	  </div>';*/
	  $output .= '<div class="see-full">
				    <a href="/services">See Full List</a>
				  </div>';
	  /*$output .= '<div class="customNavigation">
		<a class="btn prev">Previous</a>
		<a class="btn next">Next</a>
		<a class="btn play">Autoplay</a>
		<a class="btn stop">Stop</a>
	  </div>';*/
	
	  //drupal_add_css('/css/owl.carousel.css');
	  /*drupal_add_css(drupal_get_path('module', 'services_carousel_blocks') . '/css/owl.carousel.css');
	  drupal_add_css(drupal_get_path('module', 'services_carousel_blocks') . '/css/owl.theme.default.css');
	  drupal_add_js(drupal_get_path('module', 'services_carousel_blocks') .'/js/owl.carousel.js');*/
	  
	  drupal_add_js('jQuery.noConflict();
	  				jQuery(document).ready(function() {			
		
		  
		  var owl = jQuery("#service-carousel");
		  owl.owlCarousel({
			loop : true,  			
			dots: true,			
			margin : 10,
			navText: ["<i class=\"fa fa-angle-left\" aria-hidden=\"true\"></i>","<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>"],
			responsive:{
				0:{
					items:1,
					nav:true
				},
				600:{
					items:3,
					nav:true
				},
				1000:{
					items:4,
					nav:true															
				}
			}
						
		  });
		  
		});', 'inline');
	
	  return $output;
}
function services_carousel_blocks_query_filter_no_parent_alter(QueryAlterableInterface $query) {
    $query->leftJoin('field_data_field_parent_services', 'p', 'node.nid = p.entity_id');
    $query->isNull('p.field_parent_services_target_id');
}
function services_carousel_blocks_gallery_carousel(){
		$term_id = arg(2);
		
		$query = new EntityFieldQuery();
		$query->entityCondition('entity_type', 'node')
		  ->entityCondition('bundle', 'services')
		  ->propertyCondition('status', NODE_PUBLISHED)
		  ->fieldCondition('field_service_category', 'tid', $term_id)
		  //->fieldCondition('field_parent_services', 'target_id', NULL,'IS NULL')
		  ->addTag('filter_no_parent')         
		  ->propertyOrderBy('created', 'DESC')	
		  ->range(0,15); 
		//print_r($query);
		$result = $query->execute();
		//print_r($result['node']);
		if (isset($result['node'])) {
	  		$nids = array_keys($result['node']);
	  		$nodes = entity_load('node', $nids);
		}else{
			$nodes = array();
		}
	
	  $services = $nodes;
	  //print_r($services);
	  $output = '<div id="gallery-carousel" class="owl-carousel owl-theme">';
	  foreach ($services as $service) {
		  //print_r($service);
		  $alias = drupal_get_path_alias('node/'.$service->nid);
		  $banner = field_get_items('node', $service, 'field_service_image', $service->language);
		//$uri = $banner[0]['uri'];  // file path as uri: 'public://';
		$banner_img = file_create_url($banner[0]['uri']);
		$output .= '<div class="item">';
		$output .= '<a href="'.$banner_img.'" data-lightbox="carousel-gal" data-title="'.$service->title.'"><div class="product" style="background-image:url('.$banner_img.');">
					 					 
				   </div>';			
		$output .= '</a></div>';
	  }
	  $output .= '</div>';	  
	
	  
	  /*drupal_add_css(drupal_get_path('module', 'services_carousel_blocks') . '/css/owl.carousel.css');
	  drupal_add_css(drupal_get_path('module', 'services_carousel_blocks') . '/css/owl.theme.default.css');
	  drupal_add_js(drupal_get_path('module', 'services_carousel_blocks') .'/js/owl.carousel.js');*/
	  drupal_add_js('jQuery.noConflict();
	  	jQuery(document).ready(function() {
		  lightbox.option({
		  	"resizeDuration": 200,
		  	"wrapAround": true,
			"alwaysShowNavOnTouchDevices": true
		  });
		  
		  var owl = jQuery("#gallery-carousel");
		  owl.owlCarousel({
			loop : true,  			
			dots: true,			
			margin : 10,
			navText: ["<i class=\"fa fa-angle-left\" aria-hidden=\"true\"></i>","<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>"],
			responsive:{
				0:{
					items:1,
					nav:true
				},
				600:{
					items:3,
					nav:true
				},
				1000:{
					items:4,
					nav:true															
				}
			}
						
		  });
		  
		});', 'inline');
	
	  return $output;
}
function services_carousel_blocks_other_services(){
	
	$current_term = taxonomy_term_load(arg(2));
	//print_r($current_term); 
	
	if(!empty($current_term)) {
		 $query = new EntityFieldQuery();
		 $query->entityCondition('entity_type', 'taxonomy_term')
			->entityCondition('bundle', array('services'))		
			->propertyCondition('tid', $current_term->tid, '!=')
			->fieldCondition('field_private_resident_', 'value', 0, '=');
		 $result = $query->execute();
		 //$tids = array_keys($result['taxonomy_term']);
		 //print_r($result);
		 
		 if (isset($result['taxonomy_term'])) {
			$tids = array_keys($result['taxonomy_term']);
			$terms = entity_load('taxonomy_term', $tids);
		}else{
			$terms = array();
		}
	} else { 
		$vocabulary = taxonomy_vocabulary_machine_name_load('services');
		//$terms = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));
		//print_r($terms);
		$query = new EntityFieldQuery();
		 $query->entityCondition('entity_type', 'taxonomy_term')
			->entityCondition('bundle', array('services'))		
			->propertyCondition('vid', $vocabulary->vid, '=')
			->fieldCondition('field_private_resident_', 'value', 0, '=');
		 $result = $query->execute();
		 //$tids = array_keys($result['taxonomy_term']);
		 //print_r($result);
		 
		 if (isset($result['taxonomy_term'])) {
			$tids = array_keys($result['taxonomy_term']);
			$terms = entity_load('taxonomy_term', $tids);
		}else{
			$terms = array();
		}
	}
	
	$output = '<div id="other-service-wrapper"><div class="row">';
	
    foreach($terms as $term)
	{
			
		$alias = drupal_get_path_alias('taxonomy/term/'.$term->tid);
		$banner = field_get_items('taxonomy_term', $term, 'field_service_image');		
		$banner_img = file_create_url($banner[0]['uri']);
		
		$icon = field_get_items('taxonomy_term', $term, 'field_icon');		
		$icon_img = file_create_url($icon[0]['uri']);
		
	
    	$output .= '<div class="col-lg-3 col">
					<div class="other-service-box">
					<a href="/'.$alias.'">';
		//$output .= '<img class="img-responsive" src="'.$banner_img.'">';
		$output .= '<div class="service-image" style="background-image:url('.$banner_img.');"></div>';
		$output .= '<div class="img-overlay">
						<div class="overlay-content">
        					<div class="overlay-content-inner">
								<div class="term_icon" style="background-image: url('.$icon_img.');"></div>
								<div class="term_title">'.$term->name.'</div>
							</div>
						</div>					
					</div>';
        $output .= '</a></div></div>';
	
	} 
		/*== Static box for Pest Control ==*/ 
		$output .= '<div class="col-lg-3 col">
		         	<div class="other-service-box">
					<a href="/pest-control">';
		//$output .= '<img class="img-responsive" src="'.$banner_img.'">';
		$output .= '<div class="service-image" style="background-image:url('.base_path().path_to_theme().'/images/pest-control.jpg);"></div>';
		$output .= '<div class="img-overlay">
						<div class="overlay-content">
        					<div class="overlay-content-inner">
								<div class="term_icon" style="background-image: url('.base_path().path_to_theme().'/images/pest-control.png);"></div>
								<div class="term_title">Pest Control</div>	 
							</div>
						</div>		
					</div>';
        $output .= '</a></div></div>';
		/*== Static box for private Resident ==*/ 
		$output .= '<div class="col-lg-3 col">
		         	<div class="other-service-box">
					<a href="/services-residents">';
		//$output .= '<img class="img-responsive" src="'.$banner_img.'">';
		$output .= '<div class="service-image" style="background-image:url('.base_path().path_to_theme().'/images/commercial_recycling.jpg);"></div>';
		$output .= '<div class="img-overlay">
						<div class="overlay-content">
        					<div class="overlay-content-inner">
								<div class="term_icon" style="background-image: url('.base_path().path_to_theme().'/images/resident-services.png);"></div>
								<div class="term_title">
Services for Residents</div>
							</div>
						</div>		 
					</div>';
        $output .= '</a></div></div>';
	$output .= '</div></div>';
    
	return $output;
}
function services_carousel_blocks_popular_conatainer(){		
	  
	  $output = '<div id="gallery-carousel" class="owl-carousel owl-theme">';
	  
	  $output .= '<div class="item">';
	  $output .= '<div class="product" style="background-image:url(/sites/default/files/bin-container-1.jpg);">					 					 
				   </div>';			
	  $output .= '</div>';
	  
	  $output .= '<div class="item">';
	  $output .= '<div class="product" style="background-image:url(/sites/default/files/bin-container-2.jpg);">					 					 
				   </div>';			
	  $output .= '</div>';
	  
	  $output .= '<div class="item">';
	  $output .= '<div class="product" style="background-image:url(/sites/default/files/bin-container-1.jpg);">					 					 
				   </div>';			
	  $output .= '</div>';
	  
	  $output .= '<div class="item">';
	  $output .= '<div class="product" style="background-image:url(/sites/default/files/bin-container-2.jpg);">					 					 
				   </div>';			
	  $output .= '</div>';
	  
	  $output .= '<div class="item">';
	  $output .= '<div class="product" style="background-image:url(/sites/default/files/bin-container-1.jpg);">					 					 
				   </div>';			
	  $output .= '</div>';
	  $output .= '</div>';  	  
	 /*drupal_add_css(drupal_get_path('module', 'services_carousel_blocks') . '/css/owl.carousel.css');
	  drupal_add_css(drupal_get_path('module', 'services_carousel_blocks') . '/css/owl.theme.default.css');
	  drupal_add_js(drupal_get_path('module', 'services_carousel_blocks') .'/js/owl.carousel.js');*/
	  drupal_add_js('jQuery(document).ready(function() {
		  var owl = jQuery("#gallery-carousel");
		  owl.owlCarousel({
			loop : true,  			
			dots: true,			
			margin : 10,
			navText: ["<i class=\"fa fa-angle-left\" aria-hidden=\"true\"></i>","<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>"],
			responsive:{
				0:{
					items:1,
					nav:true
				},
				600:{
					items:3,
					nav:true
				},
				1000:{
					items:4,
					nav:true															
				}
			}
						
		  });
		  
		});', 'inline');
	
	  return $output;
}
function services_carousel_blocks_about_services(){
	$vocabulary = taxonomy_vocabulary_machine_name_load('services');
	$terms = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));
	
	$output ='<div class="about-blog-area">'; 
	$i = 1;
	foreach($terms as $term)
	{		
		$icon = field_get_items('taxonomy_term', $term, 'field_icon');		
		$icon_img = file_create_url($icon[0]['uri']);
		
		$output.='<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
					<div class="about-services" data-content="content-'.$i.'">
						<div class="blog-1">
							<div class="about-service-icon" style="background-image: url('.$icon_img.');"></div>
							<div class="about-service-title">'.$term->name.'</div>            
						</div>
					</div>
				</div>';
		$i++;	
		$j = $i;			
	}
	$output.='<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
					<div class="about-services" data-content="content-'.$j.'">
						<div class="blog-1">
							<div class="about-service-icon" style="background-image: url(/sites/all/themes/oxford/images/pest-control.png);"></div>
							<div class="about-service-title">Pest Control</div>            
						</div>
					</div>
				</div>';
	
	$output.='</div>';
	
	$output.='<div class="about-blog-content-area col-sm-12">';
	$i = 1;
	foreach($terms as $term)
	{
		$query = new EntityFieldQuery();
		$query->entityCondition('entity_type', 'node')
		  ->entityCondition('bundle', 'services')
		  ->propertyCondition('status', NODE_PUBLISHED)
		  ->fieldCondition('field_service_category', 'tid', $term->tid)
		  ->propertyOrderBy('created', 'DESC')	
		  ->range(0,15);
		//print_r($query);
		$result = $query->execute();
		
		if (isset($result['node'])) {
	  		$nids = array_keys($result['node']);
	  		$nodes = entity_load('node', $nids);
		}else{
			$nodes = array();
		}
	
	    $services = $nodes;	
		
		$output.='<div class="blog-content col-sm-12 content-'.$i.'" style="display:none;">        	
						<h3>'.$term->name.'</h3>'; 
						$output .='<ul>';
						foreach($services as $service)
						{
						$alias = drupal_get_path_alias('node/'.$service->nid);
						$output .='<li><a href="'.$alias.'"><i class="fa fa-angle-double-right"></i>&nbsp;'.$service->title.'</a></li>';											
						}
						$output .='</ul>';					            
		$output.='</div>';  
				  
		$i++;
		$j = $i;	
	}
		$output.='<div class="blog-content col-sm-12 content-'.$j.'" style="display:none;">        	
						<h3>Pest Control</h3>'; 
						$output .='<ul>';
						$output .='<li><i class="fa fa-angle-double-right"></i>&nbsp;Regular routine visits</li>
						           <li><i class="fa fa-angle-double-right"></i>&nbsp;Reactive emergency visits</li>
								   <li><i class="fa fa-angle-double-right"></i>&nbsp;Preventative monitoring</li>
								   <li><i class="fa fa-angle-double-right"></i>&nbsp;Preventative treatments</li>
								   <li><i class="fa fa-angle-double-right"></i>&nbsp;Reactive treatments</li>
								   <li><i class="fa fa-angle-double-right"></i>&nbsp;Recommendations on proofing and housekeeping</li>
								   <li><i class="fa fa-angle-double-right"></i>&nbsp;Bird proofing, trapping and shooting</li>
								   <li><i class="fa fa-angle-double-right"></i>&nbsp;Other proofing services</li>
								   <li><i class="fa fa-angle-double-right"></i>&nbsp;Insect identification</li>
								   <li><i class="fa fa-angle-double-right"></i>&nbsp;Electric fly killer maintenance</li>';
						$output .='</ul>';					            
		$output.='</div>';
	$output.='</div>';
	 
	
	return $output;
}
function services_carousel_blocks_pest_carousel(){		
	  
	  $output = '<div id="pest-carousel" class="owl-carousel owl-theme">';
	  
	  $output .= '<div class="item">';
	  $output .= '<a href="'.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_1.jpg" data-lightbox="carousel-pest" ><div class="product" style="background-image:url('.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_1.jpg);">					 					 
				   </div></a>';			
	  $output .= '</div>';
	  
	  $output .= '<div class="item">';
	   $output .= '<a href="'.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_2.jpg" data-lightbox="carousel-pest" ><div class="product" style="background-image:url('.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_2.jpg);">					 					 
				   </div></a>';		
	  $output .= '</div>';
	  
	  $output .= '<div class="item">';
	   $output .= '<a href="'.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_3.jpg" data-lightbox="carousel-pest" ><div class="product" style="background-image:url('.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_3.jpg);">					 					 
				   </div></a>';			
	  $output .= '</div>';
	  
	  $output .= '<div class="item">';
	   $output .= '<a href="'.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_4.jpg" data-lightbox="carousel-pest" ><div class="product" style="background-image:url('.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_4.jpg);">					 					 
				   </div></a>';		
	  $output .= '</div>';
	  
	  $output .= '<div class="item">';
	   $output .= '<a href="'.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_5.jpg" data-lightbox="carousel-pest" ><div class="product" style="background-image:url('.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_5.jpg);">					 					 
				   </div></a>';			
	  $output .= '</div>';
	  
	  $output .= '<div class="item">';
	   $output .= '<a href="'.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_6.jpg" data-lightbox="carousel-pest" ><div class="product" style="background-image:url('.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_6.jpg);">					 					 
				   </div></a>';			
	  $output .= '</div>';
	  
	  $output .= '<div class="item">';
	   $output .= '<a href="'.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_7.jpg" data-lightbox="carousel-pest" ><div class="product" style="background-image:url('.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_7.jpg);">					 					 
				   </div></a>';			
	  $output .= '</div>';
	  
	  $output .= '<div class="item">';
	   $output .= '<a href="'.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_8.jpg" data-lightbox="carousel-pest" ><div class="product" style="background-image:url('.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_8.jpg);">					 					 
				   </div></a>';			
	  $output .= '</div>';
	  
	  $output .= '<div class="item">';
	   $output .= '<a href="'.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_9.jpg" data-lightbox="carousel-pest" ><div class="product" style="background-image:url('.base_path().path_to_theme().'/images/pest-control/DS_Pest_Control_Treatments_9.jpg);">					 					 
				   </div></a>';			
	  $output .= '</div>';
	  $output .= '</div>';  	  
	
	  drupal_add_js('jQuery.noConflict();
	  	jQuery(document).ready(function() {
		  lightbox.option({
		  	"resizeDuration": 200,
		  	"wrapAround": true,
			"alwaysShowNavOnTouchDevices": true
		  });
		  var owl = jQuery("#pest-carousel");
		  owl.owlCarousel({
			loop : true,  			
			dots: true,			
			margin : 10,
			navText: ["<i class=\"fa fa-angle-left\" aria-hidden=\"true\"></i>","<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>"],
			responsive:{
				0:{
					items:1,
					nav:true
				},
				600:{
					items:3,
					nav:true
				},
				1000:{
					items:4,
					nav:true															
				}
			}
						
		  });
		  
		});', 'inline');
	
	  return $output;
}
function services_carousel_blocks_service_page_gallery()
{
	$nid = arg(1);
	$node = node_load($nid);		
	
	$gallery_images = field_get_items('node', $node, 'field_gallery_image', $node->language);
	
	$output = '<div id="gallery-carousel" class="owl-carousel owl-theme">';
	  foreach($gallery_images as $gallery_image)
	  {			  		
			$gallery_img = file_create_url($gallery_image['uri']);
		  
	  		$output .= '<div class="item"><div class="product-container">';
	  		$output .= '<a href="'.$gallery_img.'" data-lightbox="service-page-gal">				 									 						<div class="product" style="background-image:url('.$gallery_img.');">			 				   						</div>';
			if($gallery_image['title'] != "")
			{
				$output .= '<div class="product-title">'.$gallery_image['title'].'</div>';				
			}
			$output .= '</a>';			
	  		$output .= '</div></div>';
	  }
	$output .= '</div>'; 
	
	drupal_add_js('jQuery.noConflict();
	  	jQuery(document).ready(function() {
		  lightbox.option({
		  	"resizeDuration": 200,
		  	"wrapAround": true,
			"alwaysShowNavOnTouchDevices": true
		  });
	  var owl = jQuery("#gallery-carousel");
	  owl.owlCarousel({
		loop : true,  			
		dots: true,			
		margin : 10,
		navText: ["<i class=\"fa fa-angle-left\" aria-hidden=\"true\"></i>","<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>"],
		responsive:{
			0:{
				items:1,
				nav:true
			},
			600:{
				items:3,
				nav:true
			},
			1000:{
				items:4,
				nav:true															
			}
		}
					
	  });
	  
	});', 'inline'); 
	
	return $output;
}
?>  